import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paul's Letter to the Philippians</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    
       <div className={styles.hero}>
                  <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-word-of-god.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
        PHILIPPIANS
        </h1>
       <div  className={styles.image}>
       <Image 
                                src="/risen_45.png"
                                alt="Jesus teaching"
                                height={900}
                                width={2000}
                                priority
                              />
        </div>    

 <p className={styles.parables}>Even though he was writing from prison, Paul's letter contained the words "joy" or "rejoice" 14 times!</p>
                   <div className={styles.nav}>           
      <a href="https://ephesians.vercel.app/">
             <Image 
                                src="/previous.webp"
                                alt="previous"
                                 height={75}
                                width={90}
                                priority
                              />
       </a>

         <a href="https://cash.app/$JNutt367">
            <Image 
                                src="/donations_please.webp"
                                alt="contribute"
                                 height={75}
                                width={90}
                                priority
                              />
           
        </a> 
         <a href="https://colossians.vercel.app/">
           <Image 
                                src="/next.webp"
                                alt="next"
                                 height={75}
                                width={90}
                                priority
                              />
           
        </a> 
         
               </div>
               <div className={styles.iframe}>                   
               <iframe width="100%" height="315" src="https://www.youtube.com/embed/oE9qqW1-BkU?autoplay=1&mute=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                </div>                   
                                  <div className={styles.grid}>
         <div className={styles.card}>
            <h2 className={styles.chapter}>Philippians Chapter I</h2>
            <p>1 Paul and Timothy, servants of Christ Jesus,

To all God’s holy people in Christ Jesus at Philippi, together with the overseers and deacons[a]:

2 Grace and peace to you from God our Father and the Lord Jesus Christ.

Thanksgiving and Prayer
3 I thank my God every time I remember you. 4 In all my prayers for all of you, I always pray with joy 5 because of your partnership in the gospel from the first day until now, 6 being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.

7 It is right for me to feel this way about all of you, since I have you in my heart and, whether I am in chains or defending and confirming the gospel, all of you share in God’s grace with me. 8 God can testify how I long for all of you with the affection of Christ Jesus.

9 And this is my prayer: that your love may abound more and more in knowledge and depth of insight, 10 so that you may be able to discern what is best and may be pure and blameless for the day of Christ, 11 filled with the fruit of righteousness that comes through Jesus Christ—to the glory and praise of God.

Paul’s Chains Advance the Gospel
12 Now I want you to know, brothers and sisters,[b] that what has happened to me has actually served to advance the gospel. 13 As a result, it has become clear throughout the whole palace guard[c] and to everyone else that I am in chains for Christ. 14 And because of my chains, most of the brothers and sisters have become confident in the Lord and dare all the more to proclaim the gospel without fear.

15 It is true that some preach Christ out of envy and rivalry, but others out of goodwill. 16 The latter do so out of love, knowing that I am put here for the defense of the gospel. 17 The former preach Christ out of selfish ambition, not sincerely, supposing that they can stir up trouble for me while I am in chains. 18 But what does it matter? The important thing is that in every way, whether from false motives or true, Christ is preached. And because of this I rejoice.

Yes, and I will continue to rejoice, 19 for I know that through your prayers and God’s provision of the Spirit of Jesus Christ what has happened to me will turn out for my deliverance.[d] 20 I eagerly expect and hope that I will in no way be ashamed, but will have sufficient courage so that now as always Christ will be exalted in my body, whether by life or by death. 21 For to me, to live is Christ and to die is gain. 22 If I am to go on living in the body, this will mean fruitful labor for me. Yet what shall I choose? I do not know! 23 I am torn between the two: I desire to depart and be with Christ, which is better by far; 24 but it is more necessary for you that I remain in the body. 25 Convinced of this, I know that I will remain, and I will continue with all of you for your progress and joy in the faith, 26 so that through my being with you again your boasting in Christ Jesus will abound on account of me.

Life Worthy of the Gospel
27 Whatever happens, conduct yourselves in a manner worthy of the gospel of Christ. Then, whether I come and see you or only hear about you in my absence, I will know that you stand firm in the one Spirit,[e] striving together as one for the faith of the gospel 28 without being frightened in any way by those who oppose you. This is a sign to them that they will be destroyed, but that you will be saved—and that by God. 29 For it has been granted to you on behalf of Christ not only to believe in him, but also to suffer for him, 30 since you are going through the same struggle you saw I had, and now hear that I still have.

</p>
          </div>

          <div className={styles.card}>
             <h2 className={styles.chapter}>Philippians Chapter II</h2>
            <p>Imitating Christ’s Humility
2 Therefore if you have any encouragement from being united with Christ, if any comfort from his love, if any common sharing in the Spirit, if any tenderness and compassion, 2 then make my joy complete by being like-minded, having the same love, being one in spirit and of one mind. 3 Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves, 4 not looking to your own interests but each of you to the interests of the others.

5 In your relationships with one another, have the same mindset as Christ Jesus:

6 Who, being in very nature[a] God,
    did not consider equality with God something to be used to his own advantage;
7 rather, he made himself nothing
    by taking the very nature[b] of a servant,
    being made in human likeness.
8 And being found in appearance as a man,
    he humbled himself
    by becoming obedient to death—
        even death on a cross!

9 Therefore God exalted him to the highest place
    and gave him the name that is above every name,
10 that at the name of Jesus every knee should bow,
    in heaven and on earth and under the earth,
11 and every tongue acknowledge that Jesus Christ is Lord,
    to the glory of God the Father.

Do Everything Without Grumbling
12 Therefore, my dear friends, as you have always obeyed—not only in my presence, but now much more in my absence—continue to work out your salvation with fear and trembling, 13 for it is God who works in you to will and to act in order to fulfill his good purpose.

14 Do everything without grumbling or arguing, 15 so that you may become blameless and pure, “children of God without fault in a warped and crooked generation.”[c] Then you will shine among them like stars in the sky 16 as you hold firmly to the word of life. And then I will be able to boast on the day of Christ that I did not run or labor in vain. 17 But even if I am being poured out like a drink offering on the sacrifice and service coming from your faith, I am glad and rejoice with all of you. 18 So you too should be glad and rejoice with me.

Timothy and Epaphroditus
19 I hope in the Lord Jesus to send Timothy to you soon, that I also may be cheered when I receive news about you. 20 I have no one else like him, who will show genuine concern for your welfare. 21 For everyone looks out for their own interests, not those of Jesus Christ. 22 But you know that Timothy has proved himself, because as a son with his father he has served with me in the work of the gospel. 23 I hope, therefore, to send him as soon as I see how things go with me. 24 And I am confident in the Lord that I myself will come soon.

25 But I think it is necessary to send back to you Epaphroditus, my brother, co-worker and fellow soldier, who is also your messenger, whom you sent to take care of my needs. 26 For he longs for all of you and is distressed because you heard he was ill. 27 Indeed he was ill, and almost died. But God had mercy on him, and not on him only but also on me, to spare me sorrow upon sorrow. 28 Therefore I am all the more eager to send him, so that when you see him again you may be glad and I may have less anxiety. 29 So then, welcome him in the Lord with great joy, and honor people like him, 30 because he almost died for the work of Christ. He risked his life to make up for the help you yourselves could not give me.</p>
          </div>

          <div
            className={styles.card}
          >
  <h2 className={styles.chapter}>Philippians Chapter III</h2>
            <p>No Confidence in the Flesh
3 Further, my brothers and sisters, rejoice in the Lord! It is no trouble for me to write the same things to you again, and it is a safeguard for you. 2 Watch out for those dogs, those evildoers, those mutilators of the flesh. 3 For it is we who are the circumcision, we who serve God by his Spirit, who boast in Christ Jesus, and who put no confidence in the flesh— 4 though I myself have reasons for such confidence.

If someone else thinks they have reasons to put confidence in the flesh, I have more: 5 circumcised on the eighth day, of the people of Israel, of the tribe of Benjamin, a Hebrew of Hebrews; in regard to the law, a Pharisee; 6 as for zeal, persecuting the church; as for righteousness based on the law, faultless.

7 But whatever were gains to me I now consider loss for the sake of Christ. 8 What is more, I consider everything a loss because of the surpassing worth of knowing Christ Jesus my Lord, for whose sake I have lost all things. I consider them garbage, that I may gain Christ 9 and be found in him, not having a righteousness of my own that comes from the law, but that which is through faith in[a] Christ—the righteousness that comes from God on the basis of faith. 10 I want to know Christ—yes, to know the power of his resurrection and participation in his sufferings, becoming like him in his death, 11 and so, somehow, attaining to the resurrection from the dead.

12 Not that I have already obtained all this, or have already arrived at my goal, but I press on to take hold of that for which Christ Jesus took hold of me. 13 Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead, 14 I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.

Following Paul’s Example
15 All of us, then, who are mature should take such a view of things. And if on some point you think differently, that too God will make clear to you. 16 Only let us live up to what we have already attained.

17 Join together in following my example, brothers and sisters, and just as you have us as a model, keep your eyes on those who live as we do. 18 For, as I have often told you before and now tell you again even with tears, many live as enemies of the cross of Christ. 19 Their destiny is destruction, their god is their stomach, and their glory is in their shame. Their mind is set on earthly things. 20 But our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ, 21 who, by the power that enables him to bring everything under his control, will transform our lowly bodies so that they will be like his glorious body.</p>
          </div>

          <div
            className={styles.card}
          >
             <h2 className={styles.chapter}>Philippians Chapter IV</h2>
            <p>
            Closing Appeal for Steadfastness and Unity
4 Therefore, my brothers and sisters, you whom I love and long for, my joy and crown, stand firm in the Lord in this way, dear friends!

2 I plead with Euodia and I plead with Syntyche to be of the same mind in the Lord. 3 Yes, and I ask you, my true companion, help these women since they have contended at my side in the cause of the gospel, along with Clement and the rest of my co-workers, whose names are in the book of life.

Final Exhortations
4 Rejoice in the Lord always. I will say it again: Rejoice! 5 Let your gentleness be evident to all. The Lord is near. 6 Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. 7 And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.

8 Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things. 9 Whatever you have learned or received or heard from me, or seen in me—put it into practice. And the God of peace will be with you.

Thanks for Their Gifts
10 I rejoiced greatly in the Lord that at last you renewed your concern for me. Indeed, you were concerned, but you had no opportunity to show it. 11 I am not saying this because I am in need, for I have learned to be content whatever the circumstances. 12 I know what it is to be in need, and I know what it is to have plenty. I have learned the secret of being content in any and every situation, whether well fed or hungry, whether living in plenty or in want. 13 I can do all this through him who gives me strength.

14 Yet it was good of you to share in my troubles. 15 Moreover, as you Philippians know, in the early days of your acquaintance with the gospel, when I set out from Macedonia, not one church shared with me in the matter of giving and receiving, except you only; 16 for even when I was in Thessalonica, you sent me aid more than once when I was in need. 17 Not that I desire your gifts; what I desire is that more be credited to your account. 18 I have received full payment and have more than enough. I am amply supplied, now that I have received from Epaphroditus the gifts you sent. They are a fragrant offering, an acceptable sacrifice, pleasing to God. 19 And my God will meet all your needs according to the riches of his glory in Christ Jesus.

20 To our God and Father be glory for ever and ever. Amen.

Final Greetings
21 Greet all God’s people in Christ Jesus. The brothers and sisters who are with me send greetings. 22 All God’s people here send you greetings, especially those who belong to Caesar’s household.

23 The grace of the Lord Jesus Christ be with your spirit. Amen.[a]
            </p>
          </div>

        



        </div>
</div>
      </main>

<main id="jude" className={styles.main}>
       
        <div id="#" className={styles.hero}>
                <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-word-of-god.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        <h1 className={styles.title}>
       JUDE
        </h1>
          <div className={styles.image}>
                           <Image 
                                                    src="/jude.png"
                                                    alt="john_hero.png"
                                                    height={900}
                                                    width={2000}
                                                    priority
                                                  />
                          

                        </div>
    <p className={styles.parables}>

         Jude will have description soon
</p>                                                      
                  <div className={styles.nav2}>           
      <a href="https://romans-five.vercel.app/#james">
             <Image 
                                src="/previous.webp"
                                alt="prev"
                                 height={75}
                                width={90}
                                priority
                              />
       </a>

        
      <a href="https://cash.app/$JNutt367">
              <Image className={styles.arrow}
                                src="/donations_please.webp"
                                alt="donations_please.webp"
                                height={75}
                                width={90}
                                priority
                              /> 
       </a>
         <a href="https://first-thessalonians.vercel.app/">
           <Image 
                                src="/next.webp"
                                alt="next"
                                 height={75}
                                width={90}
                                priority
                              />
           
        </a> 
         
               </div>
                               <div className={styles.iframe}> 
                                    <iframe width="100%" height="315" src="https://www.youtube.com/embed/6UoCmakZmys?autoplay=1&mute=1" title="YouTube video player" frameborder="1" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>                    
                                  </div>
                                  
                              
        <div className={styles.grid2}>
          <div className={styles.card2}>
           <h2  className={styles.chapter2}>Jude</h2>
                                    <p> 
                                                                                                                                                                                              1 Jude, a servant of Jesus Christ and a brother of James,
                                                                              
                                                                              To those who have been called, who are loved in God the Father and kept for[a] Jesus Christ:
                                                                              
                                                                              2 Mercy, peace and love be yours in abundance.
                                                                              
                                                                              The Sin and Doom of Ungodly People
                                                                              3 Dear friends, although I was very eager to write to you about the salvation we share, I felt compelled to write and urge you to contend for the faith that was once for all entrusted to God’s holy people. 4 For certain individuals whose condemnation was written about[b] long ago have secretly slipped in among you. They are ungodly people, who pervert the grace of our God into a license for immorality and deny Jesus Christ our only Sovereign and Lord.
                                                                              
                                                                              5 Though you already know all this, I want to remind you that the Lord[c] at one time delivered his people out of Egypt, but later destroyed those who did not believe. 6 And the angels who did not keep their positions of authority but abandoned their proper dwelling—these he has kept in darkness, bound with everlasting chains for judgment on the great Day. 7 In a similar way, Sodom and Gomorrah and the surrounding towns gave themselves up to sexual immorality and perversion. They serve as an example of those who suffer the punishment of eternal fire.
                                                                              
                                                                              8 In the very same way, on the strength of their dreams these ungodly people pollute their own bodies, reject authority and heap abuse on celestial beings. 9 But even the archangel Michael, when he was disputing with the devil about the body of Moses, did not himself dare to condemn him for slander but said, “The Lord rebuke you!”[d] 10 Yet these people slander whatever they do not understand, and the very things they do understand by instinct—as irrational animals do—will destroy them.
                                                                              
                                                                              11 Woe to them! They have taken the way of Cain; they have rushed for profit into Balaam’s error; they have been destroyed in Korah’s rebellion.
                                                                              
                                                                              12 These people are blemishes at your love feasts, eating with you without the slightest qualm—shepherds who feed only themselves. They are clouds without rain, blown along by the wind; autumn trees, without fruit and uprooted—twice dead. 13 They are wild waves of the sea, foaming up their shame; wandering stars, for whom blackest darkness has been reserved forever.
                                                                              
                                                                              14 Enoch, the seventh from Adam, prophesied about them: “See, the Lord is coming with thousands upon thousands of his holy ones 15 to judge everyone, and to convict all of them of all the ungodly acts they have committed in their ungodliness, and of all the defiant words ungodly sinners have spoken against him.”[e] 16 These people are grumblers and faultfinders; they follow their own evil desires; they boast about themselves and flatter others for their own advantage.
                                                                              
                                                                              A Call to Persevere
                                                                              17 But, dear friends, remember what the apostles of our Lord Jesus Christ foretold. 18 They said to you, “In the last times there will be scoffers who will follow their own ungodly desires.” 19 These are the people who divide you, who follow mere natural instincts and do not have the Spirit.
                                                                              
                                                                              20 But you, dear friends, by building yourselves up in your most holy faith and praying in the Holy Spirit, 21 keep yourselves in God’s love as you wait for the mercy of our Lord Jesus Christ to bring you to eternal life.
                                                                              
                                                                              22 Be merciful to those who doubt; 23 save others by snatching them from the fire; to others show mercy, mixed with fear—hating even the clothing stained by corrupted flesh.[f]
                                                                              
                                                                              Doxology
                                                                              24 To him who is able to keep you from stumbling and to present you before his glorious presence without fault and with great joy— 25 to the only God our Savior be glory, majesty, power and authority, through Jesus Christ our Lord, before all ages, now and forevermore! Amen.
                                    </p>
          </div>

         
          <div className={styles.card2}
          >
            <h2 className={styles.chapter2}>!Explaination of Layout!</h2>
            <p>
            I have appended 1 Thessalonians to the bottom of 1 corinthians...
            I have appended 2 Thessalonians to the bottom of 2 corinthians...
            I have appended 1 Timothy to the bottom of the gospel of Matthew...
            I have appended 2 Timothy to the bottom of the gospel of Mark...
            I have appended Titus to the bottom of the gospel of Luke...
            I have appended Philemon to the bottom of the gospel of John...
            I have appended Hebrews to the bottom of the book of Acts ...
            I have appended James to the bottom of Romans ...
            I have appended I Peter to the bottom of Galatians
            I have appended II Peter to the bottom of I Peter ...
            I have appended I John to the bottom of Ephesians ...  
            I have appended II John to the bottom of I John ...
            I have appended III John to the bottom of II John ...
            I have appended Jude to the bottom of Philippians ...
                        This has completed the New Testament portion of this Bible App...Praise God for the ability to code, publish & deploy this passion project!!
     </p>
          </div>


     

        </div>
</div>
        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>
      </main>


  
    </div>
  )
}
